// <auto-generated />
using Api;
using Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240119183024_aplicandoDataNotations")]
    partial class aplicandoDataNotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Stock", b =>
                {
                    b.Property<string>("StockId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<double>("CagrIncome")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("CagrProfit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("DividendYield")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EnterpriseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("NetDebtEbtida")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("NetMargin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Pl")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Pvl")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Roe")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
